### ISSUE TITLE
[doc] 4.5  Installing Database on valuga01: Instance Number issue?

### ISSUE THREAD

**Issue by ldevulder** [SUSE/suse-best-practices#129]
4.5  Installing Database on valuga01:

https://documentation.suse.com/sbp/all/html/SAP_S4HA10_SetupGuide-SLE15/index.html#_installing_database_on_valuga01

If I set the Instance Number to 00 as the doc said, then I have a `Instance Number "00" is already in use by local SAP System EN2` error. As far as I understand each SAP instance should have a unique ID, so in that cas 00 is already used by ASCS, no? And as the `/usr/sap/EN2/SYS` and `sapmnt` directories are shared across all nodes (see [here](https://documentation.suse.com/sbp/all/html/SAP_S4HA10_SetupGuide-SLE15/images/sles4sap_ap1809_fs.svg)), then HANA DB installer detect it.

Or did I do something wrong?

**Comment by fmherschel** [comment]
You missed the point that we are installing the database (by intention) on a seperate server. The InstanceNumber is only unique per linux server system (node).
If you install SAP HANA on the same system as ASCS and ERS you are modelling a complete different cluster.
As the SAP S/4 HANA HA certification just focuses at the Application Server Level (here ASCS/ERS plus multiple AS) the
database needs to be installed on a different system. Otherwise the test expectations needs to be changed.

**Comment by fmherschel** [comment]
I hope that explained why InstanceNumber 00 could be used twice.

**Comment by ldevulder** [comment]
> I hope that explained why InstanceNumber 00 could be used twice.

No because in my case I installed SAP HANA on a different system. I have 3 servers, one for SAP HANA/PAS/AAS and a 2-nodes cluster for ASCS/ERS. But as I explained it seems that the duplicate ID is found because `/usr/sap/EN2/SYS` is a NFS share mounted on all nodes.

Is `/usr/sap/EN2/SYS` should be mounted on SAP HANA server also or not?

**Comment by fmherschel** [comment]
Please follow our documentation! As ASCS/ERS will NOT be running on valuga01 at any time there is no doublet on the 
InstanceNumber. Please also check that the SID for the SAP HANA is different to the one used for ASCS/ERS!
