### ISSUE TITLE
edit source links broken in Migrate SUSE Linux Enterprise Server 12 SP1 to SUSE Linux Enterprise Server for SAP Applications 12 SP1

### ISSUE THREAD

**Issue by jamesongithub** [SUSE/suse-best-practices#155]
https://documentation.suse.com/sbp/all/single-html/SBP-SLES12SP1-SAP-migrationguide/

all edit source links seem to be broken

https://github.com/SUSE/suse-best-practices/blob/master/xml/MAIN-SBP-SLES12SP1-SAP-migrationguide.xmlMAIN-SBP-SLES12SP1-SAP-migrationguide.xml goes to github 404

@mfriesenegger

**Comment by chabowski** [comment]
@jamesongithub  @mfriesenegger 

Hi James, thanks for reporting this issue. It seems to exist for all SBPs that have the "Edit Source" option enabled. The issue is that the xml file name gets doubled in the URL. Seems to be a stylesheet issue. We are investigating further, and try to fix it.

For now, if you need to edit the source, you can go to the file in GitHub directly  
https://github.com/SUSE/suse-best-practices/blob/master/xml/MAIN-SBP-SLES12SP1-SAP-migrationguide.xml

Thanks again!
Meike

**Comment by sknorr** [comment]
This has been fixed, fixes are online.
