### ISSUE TITLE
Is it really "Enlightment" of VMs?

### ISSUE THREAD

**Issue by chabowski** [SUSE/suse-best-practices#180]
https://github.com/SUSE/suse-best-practices/blob/018d4f60114b3025fc52fc0475d406b0927b5396/xml/MAIN-SBP-AMD-EPYC-3-SLES15SP2.xml#L2174

@gormanm @dfaggioli 

Is it really "Enlightment of VMs"?? I am well aware that tech terms can be strange ;-) - but we had a discussion internally, and after doing some research, we got only "enlightenment" back as results in relation with virtualization.

Thanks very much for clarification!

**Comment by gormanm** [comment]
I think this may be a reflection of Dario's style as I'm not familiar with the term itself. I interpreted to mean topology pass-through similar to device pass-through and I think that was the intent. Dario?

**Comment by dfaggioli** [comment]
> https://github.com/SUSE/suse-best-practices/blob/018d4f60114b3025fc52fc0475d406b0927b5396/xml/MAIN-SBP-AMD-EPYC-3-SLES15SP2.xml#L2174
> 
> @gormanm @dfaggioli
> 
> Is it really "Enlightment of VMs"?? I am well aware that tech terms can be strange ;-) - but we had a discussion internally, and after doing some research, we got only "enlightenment" back as results in relation with virtualization.
> 
It definitely is "enlightenment", and not "enlightment". The latter, I don't think is a word. And yes, I am aware that it is me that wrote it, so I can only apologize for not being able to type / write in English :-(

> Thanks very much for clarification!
>
Well, thanks to you, and sorry if I didn't catch this while reviewing and running a spell-check on the paper myself (and I'm particularly sad to hear that this took what looks to be a considerable amount of your time :-/ )

**Comment by dfaggioli** [comment]
> I think this may be a reflection of Dario's style as I'm not familiar with the term itself. I interpreted to mean topology pass-through similar to device pass-through and I think that was the intent. Dario?

Yes. Well, if I've understood well, the bulk of the issue here is me not being able to write in English. :-( But from a semantic point of view, in virtualization, we refer to "enlightening" whenever we make the VM aware of something that, while strictly not necessary for functional correctness, it may result in some advantages, e.g., in terms of improved performance.

Such "improved awareness" could be about making the OS in the VM know that it is running virtualized (which then enables the use of some paravirtualization-based techniques, typically for clocks, timers, interrupts, etc) or it can come from --as you say yourself-- the fact that we define a particular virtual topology, which matches the one of the host in some specific way.

Some quick and random examples, just for reference:

- https://archive.fosdem.org/2019/schedule/event/vai_enlightening_kvm/attachments/slides/2860/export/events/attachments/vai_enlightening_kvm/slides/2860/vkuznets_fosdem2019_enlightening_kvm.pdf
- https://www.researchgate.net/publication/261511421_A_Performance_Comparison_between_Enlightenment_and_Emulation_in_Microsoft_Hyper-V
- https://events19.linuxfoundation.cn/wp-content/uploads/2017/11/Use-Hyper-V-Enlightenments-to-Increase-KVM-VM-Performance_Density_Chao-Peng.pdf

As you can see the term is quite common when MS Hyper-V virtualization solutions are involved, at least if we're speaking about KVM.

In the Xen world, it's even more widely used (even with Hyper-V out of the picture):

- https://wiki.xenproject.org/wiki/Xen_Project_Beginners_Guide#What_is_this_Xen_Project_software_all_about.3F (see <<Paravirtualization uses modified guest operating systems that we refer to as "enlightened" guests.>>
- https://elixir.bootlin.com/linux/latest/source/arch/x86/xen/enlighten.c (and other files, such as enlighten_hvm.c, enlighten_pv.c and enlighten_pvh.c)
-

**Comment by chabowski** [comment]
Hi Dario,

I found "enlightenment" in this content quite often via search. "Enlightening" might also be good. But we had "enlightment" throughout that chapter :-), and I wanted to make sure that it is not a term but probably a typo. 😁

And your English is great! Our native English reviewer did not find much.

Kind regards,
Meike



Von meinem/meiner Galaxy gesendet



-------- Ursprüngliche Nachricht --------
Von: Dario Faggioli ***@***.***>
Datum: 12.03.21 09:26 (GMT+01:00)
An: SUSE/suse-best-practices ***@***.***>
Cc: Meike Chabowski ***@***.***>, Author ***@***.***>
Betreff: Re: [SUSE/suse-best-practices] Is it really "Enlightment" of VMs? (#180)


I think this may be a reflection of Dario's style as I'm not familiar with the term itself. I interpreted to mean topology pass-through similar to device pass-through and I think that was the intent. Dario?

Yes. Well, if I've understood well, the bulk of the issue here is me not being able to write in English. :-( But from a semantic point of view, in virtualization, we refer to "enlightening" whenever we make the VM aware of something that, while strictly not necessary for functional correctness, it may result in some advantages, e.g., in terms of improved performance.

Such "improved awareness" could be about making the OS in the VM know that it is running virtualized (which then enables the use of some paravirtualization-based techniques, typically for clocks, timers, interrupts, etc) or it can come from --as you say yourself-- the fact that we define a particular virtual topology, which matches the one of the host in some specific way.

Some quick and random examples, just for reference:

  *   https://archive.fosdem.org/2019/schedule/event/vai_enlightening_kvm/attachments/slides/2860/export/events/attachments/vai_enlightening_kvm/slides/2860/vkuznets_fosdem2019_enlightening_kvm.pdf
  *   https://www.researchgate.net/publication/261511421_A_Performance_Comparison_between_Enlightenment_and_Emulation_in_Microsoft_Hyper-V
  *   https://events19.linuxfoundation.cn/wp-content/uploads/2017/11/Use-Hyper-V-Enlightenments-to-Increase-KVM-VM-Performance_Density_Chao-Peng.pdf

As you can see the term is quite common when MS Hyper-V virtualization solutions are involved, at least if we're speaking about KVM.

In the Xen world, it's even more widely used (even with Hyper-V out of the picture):

  *   https://wiki.xenproject.org/wiki/Xen_Project_Beginners_Guide#What_is_this_Xen_Project_software_all_about.3F (see <<Paravirtualization uses modified guest operating systems that we refer to as "enlightened" guests.>>
  *   https://elixir.bootlin.com/linux/latest/source/arch/x86/xen/enlighten.c (and other files, such as enlighten_hvm.c, enlighten_pv.c and enlighten_pvh.c)
