### ISSUE TITLE
[doc]  

### ISSUE THREAD

**Issue by 888jonno** [SUSE/suse-best-practices#232]
:

https://documentation.suse.com/sbp/all/html/SLES4SAP-hana-sr-guide-PerfOpt-15/index.html#id-1.12.6.7.2.4

I'm pretty sure this should read "Restart the HANA database (now secondary) on node 2 as root." rather than "node 1"

**Comment by chabowski** [comment]
@fmherschel @lpinne Hi Fabian and Lars!
Could you please check the test cases at:
https://documentation.suse.com/sbp/all/html/SLES4SAP-hana-sr-guide-PerfOpt-15/index.html#id-test-cases-for-semi-automation 
regarding the comment above? Thank you very much! I have this issue as question for now.

**Comment by fmherschel** [comment]
@chabowski Sorry currently to work on that.

**Comment by lpinne** [comment]
Hi,

unfortunately the given link does not work anymore.

However, we had a typo in the testcases. But it was the other way round: node 1 instead of node 2.
Now it matches:
---
. Manually register the old primary (on node 1) with the new primary after takeover (on node 2) as _{refsidadm}_.
. Restart the {HANA} database (now secondary) on node 1 as root.

.  Manually register the old primary (on node 2) with the new primary
.  Restart the {HANA} database (now secondary) on node 2 as root.

.  Manually register the old primary (on nodel 1) with the new primary
.  Restart the {HANA} database (now secondary) on node 1 as root.

.  Manually register the old primary (on node 2) with the new primary
.  Restart the {HANA} database (now secondary) on node 2 as root.

.  Manually register the old primary (on node 1) with the new primary after takeover (on node 2) as _{refsidadm}_.
.  Restart the {HANA} database (now secondary) on node 1 as root.

.  Manually register the old primary (on node 2) with the new primary
.  Restart the {HANA} database (now secondary) on node 2 as root.
--- 
PR #380 should fix that.

If that was not the reported issue, please do not hesitate to report as new one.
Thanks a lot!

Regards,
Lars
