### ISSUE TITLE
[doc]  

### ISSUE THREAD

**Issue by anmozz** [SUSE/suse-best-practices#301]
:

https://documentation.suse.com/sbp/all/html/SLES4SAP-hana-sr-guide-PerfOpt-15/index.html#id-1.12.6.5.2.4

On Example 17, Recovery procedure, point 2:
mistaken:
Restart the HANA database (now secondary) on node **1** as root.
should be:
Restart the HANA database (now secondary) on node **2** as root.

**Comment by chabowski** [comment]
@fmherschel @lpinne would you please have a quick look and verify? I would then fix that issue. Thanks!

**Comment by lpinne** [comment]
Hi,

anmozz is right.
Since the database is stopped on node2, it has to be registered and started on node2.

Regards,
Lars

---
10.1.2 Test: Stop primary database on site B (node 2)

Component:
    Primary Database

Description:
    The primary HANA database is stopped during normal cluster operation.

Test Procedure:

    Stop the database gracefully as <sid>adm.
    suse02:~> HDB stop

Recovery Procedure:

    Manually register the old primary (on node 2) with the new primary after takeover (on node 1) as <sid>adm.

    suse02:~> hdbnsutil -sr_register --remoteHost=suse01 --remoteInstance=10 \
              --replicationMode=sync --operationMode=logreplay \
              --name=ROT

Restart the HANA database (now secondary) on node 2 as root.

# crm resource refresh rsc_SAPHana_HA1_HDB10 suse02
---

**Comment by chabowski** [comment]
Bug is fixed, also in version 12 of the document. Changes will be published with next build of the repo. Closing bug.
