### ISSUE TITLE
[doc] Example&nbsp;13:  Checking the Operation Mode 

### ISSUE THREAD

**Issue by roseswe** [SUSE/suse-best-practices#94]
Example&nbsp;13:  Checking the Operation Mode :

https://documentation.suse.com/sbp/all/single-html/SLES4SAP-hana-sr-guide-PerfOpt-12/#id-1.9.7.5

Is with both "Check both global.ini files and add the operation mode if needed."  the SYSTEMDB and TENANT refereed or the Node1 and Node2 (should be explained). Customers loose here a lot of time with guessing

**Comment by chabowski** [comment]
@fmherschel @lpinne @pirat013 
Ralph Roth has submitted several issues/questions  (via the "report a bug" link in the doc which opens a GitHub issue).
Can you please have a look? This is his first question/issue.
Thanks very much!

**Comment by fmherschel** [comment]
The global.ini file is sigular per SAP HANA database (so for all tenants) at least this is my point of view. So the statement is clear for me.

**Comment by roseswe** [comment]
As said I mirror only customer experience here

**Comment by fmherschel** [comment]
We even provide the full and clear Path for the global.ini: /hana/shared/<SID>/global/hdb/custom/config/

**Comment by fmherschel** [comment]
The markdown damaged my last comment, fixed it now. So the path only depends on the SID not the tennant. The is no global.ini per tennant.

**Comment by lpinne** [comment]
@roseswe: fmherschel alraedy fixed the error. We also might change the wording to something like:
---
Check the global.ini file on both nodes and add the operation mode if needed.
--- 
May I add an note, because there might be a pattern:
We have to distinguish between errors in our documents and reader's perception.
If a wrong path is given that is an error.
If a reader expects information about HANA configuration, that might be a misperception.
The mentioned config changes and actions at HANA are all just examples. At customer site everything related to
HANA needs to be planned and done by certified admins. If such an expert is not available, the consultant or
implementation partner might decide to take over some tasks. In that case he/she needs to have the knowlegde,
of course.

**Comment by chabowski** [comment]
Hi @fmherschel and @lpinne,
can we close this issue, or is this still open and an enhancement that is to be expected for the next version?

Thanks very much, and kind regards,
Meike

**Comment by lpinne** [comment]
see setup guides
